Repository Automattic/vip-go-node-skeleton, pull requests merged in 2021-12, with the labels that each got.

#26 DECOUPLED-42: add a static example
  examples/.gitignore
  examples/static/README.md
  examples/static/package.json
  examples/static/src/index.js
  examples/static/src/public/assets/hello.jpg
  examples/static/src/public/assets/styles.css
  examples/static/src/public/index.html
Labels: [Status] Ready to Merge, [Type] Enhancement

#27 DOCS-489 - hotlink Express in Readme to the Express documentation
  examples/static/README.md
Labels: [Status] Needs Review, [Type] Enhancement

#29 Add Gatsby example
  examples/gatsby/.gitignore
  examples/gatsby/README.md
  examples/gatsby/gatsby-config.js
  examples/gatsby/package.json
  examples/gatsby/src/pages/404.js
  examples/gatsby/src/pages/index.js
  examples/gatsby/static/cache-healthcheck
Labels: [Status] Needs Review
